### ISSUE TITLE
Public/neat-things

### ISSUE THREAD

**Issue by nescafe-gold** [Barbaross93/Genome#11]
Hi,

I have managed to replicate everything I like from your config into mine except for the colorscheme. Can you please upload your Public/neat-things folder? I used the colorscheme from "Arctic Ice Studio" but it is missing color16, color17, color18, and it is not as dark as yours. I also need the neat-things folder because nord.sh is referenced in the bspwmrc.

**Comment by Barbaross93** [comment]
As mentioned in the README, the only other color besides the palette from Arctic Ice Studios is "#232831". It's referenced as color16. Otherwise, color17 and color18 are two other colors from the original palette, namely, "#5e81ac" and "#d08770" respectively. Hope that helps!
