### ISSUE TITLE
Lockscreen

### ISSUE THREAD

**Issue by AbbasSrour** [Barbaross93/Genome#12]
Hello, greet config btw I wanted to ask how did you achieve the box that houses the image ring, time and username in the i3lockscreen, I have been playing lockscreen.sh but I can't seem to find how did you achieve that.

**Comment by Barbaross93** [comment]
Hi there! Glad you like the setup. I just drew the shapes in gimp. It took some trial and error to get the ring to match with i3lock's indicator.
