### ISSUE TITLE
Small icon questions

### ISSUE THREAD

**Issue by Qpernicus** [Barbaross93/Genome#15]
1) The iconset in you VSCode instance, which set is that.
2) The "launcher" icon, how did you create this? It seems the Nord-DNA image, but how did you make it show in polybar?
3) What did you edit in Dribbblish theme to get only icons in Spotify.

**Comment by Barbaross93** [comment]
1. I'm sorry, I don't quite remember. I think it was one of the included icon sets; "minimal" or something like that
2. It's an icon from Font Awesome
3. I don't recall making edits for that. I remember only changing the fonts. Sorry :(
